import Head from 'next/head'
import { Inter } from '@next/font/google'
import { TabsHeader } from "src/components";

export default function Home() {
  return (
    <div className='flex flex-1 w-full overflow-y-scroll'>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <TabsHeader />
    </div>
  )
}
